name: checkov

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every at 00:00 on Sunday UTC time.
on:
    push:
    schedule:
    - cron: '0 0 * * 0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scan"
  scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
      - uses: actions/checkout@v3

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
            soft_fail: true
            output_format: json
            output_file_path: results.json
          
      - name: Import results to ScanDog
        uses: scandogio/scandog-import@v1.0
        with:
            ci_run_id: ${{ github.run_id }}
            report_file: results.json
            workflow_id: c81851fb35e8dde5737fc24bbad47272
            scan_type: IaC Scanner
            scanner: checkov
            backend_api_token: ${{ secrets.DEV_BACKEND_API_TOKEN }}
            backend_url: ${{ secrets.DEV_BACKEND_URL }}
