# Scanners: Trivy
# Generated for GITHUB by ScanDog
name: Container Scanner Scanner Pipeline
on:
  push:
    branches:
      - master

jobs:
  scandog_trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nginx:stable-bookworm-perl
          format: 'json'
          output: 'trivy-results.json'
      - name: Import results to ScanDog
        uses: scandogio/scandog-import@v1.0
        with:
          ci_run_id: ${{ github.run_id }}
          report_file: trivy-results.json
          workflow_id: "2d92e4995e58dfa00f667a4882e93ff1"
          scan_type: Container Scanner
          scanner: Trivy
          backend_api_token: ${{ secrets.SCANDOG_BACKEND_API_TOKEN }}
          backend_url: ${{ secrets.SCANDOG_BACKEND_URL }}
